Structure updates and code review
wickathou/new-york-times pull request #2
Opened 2019-09-27 00:00 UTC by wickathou

2019-09-27 05:06 UTC, uche-inyama requested changes
## Hi team, nice work,

Everything looks almost fine, please make these updates :slightly_smiling_face: 

- [x] Your Html document is not valid, there are errors showing up, when passed through [html validator](https://validator.w3.org).

- [x] The size of your first embedded image is larger when compared with the [original website](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html) 

- [x] The images in **The theory of inflation section** is not coming up

![Screenshot from 2019-09-27 05-52-22](https://user-images.githubusercontent.com/46329537/65743329-01495e80-e0ec-11e9-97ef-815a184a1785.png)


- [x] Implement the extra login in your footer section,  It should have a fixed position (it sticks to the bottom part of the screen).

![Screenshot from 2019-09-27 06-01-37](https://user-images.githubusercontent.com/46329537/65743449-8e8cb300-e0ec-11e9-87a8-4700b9270e1c.png)


After Implementing these changes, submit another form for a code review.

**```Happy coding```** :slightly_smiling_face:

2019-09-27 15:07 UTC, wickathou commented
Hey Henry, thanks for the review. Just one observation about the validator, the original webpage doesn't have h2-h3 on the sections that the warnings are being shown, so I think it doesn't make sense to add it if the real page doesn't have it either.

With respect of the login in the footer, it's an ad, which based on the challenge we don't have to do any add related content.

2019-09-27 21:24 UTC, ebukaume commented
Hi @wickathou and @jfariasf :wave: 

Good job so far. However, there are a few things left before we can go green on this project.

**Navigation Bar**

- [ ] The NY Times logo is a link.
- [ ] It should have a fixed position (it sticks to the top part of the screen).

**Others**

- [ ] The project has a descriptive README.md. See [template](https://github.com/othneildrew/Best-README-Template) for a guide.
- [ ] No `!important` overusing. See this [article](https://speckyboy.com/good-bad-css-practices/) for basis CSS dos and don'ts

**Kindly submit another code review request form after fixing these issues.**

**Happy coding, guys** :v:

2019-09-27 22:21 UTC, wickathou commented
> Hi @wickathou and @jfariasf 👋
> 
> Good job so far. However, there are a few things left before we can go green on this project.
> 
> **Navigation Bar**
> 
> * [x]  The NY Times logo is a link.
> * [x]  It should have a fixed position (it sticks to the top part of the screen).
> 
> **Others**
> 
> * [x]  The project has a descriptive README.md. See [template](https://github.com/othneildrew/Best-README-Template) for a guide.
> * [x]  No `!important` overusing. See this [article](https://speckyboy.com/good-bad-css-practices/) for basis CSS dos and don'ts
> 
> **Kindly submit another code review request form after fixing these issues.**
> 
> **Happy coding, guys** ✌️

2019-09-28 13:28 UTC, bolah2009 requested changes
# Hi Team :wave: 

### You have done an awesome job with this project. :clap: 

#### [The clone](https://rawcdn.githack.com/wickathou/new-york-times/d91b57dfdb1d0870654ea7afb1aa774a9400f20f/index.html) looks good to me and uses CSS positioning effectively. :100: :smile: 

However, a few changes need to be implemented before a :+1: 
- Let's make the navbar fixed positioned. This makes sense for long pages, it will be easier for users to navigate the page without the need to scroll back up the page. Also, note that the main objective of this project is CSS Positioning. :blush: 
- Let's wrap the NY Times logo with an anchor tag. This is reasonable as the brand logo is typically the link to the homepage of the website.
- As @ebukaume suggested, using a descriptive readme make the repo looks more professional. README file is the first impression of this repository, it is the book cover people want to judge the book with :wink:
  > Remember about descriptive README file.
- Let's fix all [these HTML Validation warnings/errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Frawcdn.githack.com%2Fwickathou%2Fnew-york-times%2Fd91b57dfdb1d0870654ea7afb1aa774a9400f20f%2Findex.html). 
Most (I think all) is about the use of `section` element without a heading element (`h2`-`h6`). 
Is it possible we are overusing `section` element? :thinking: 
Please, learn more about [`section` element here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section). Also note this section :point_down: 
  > ### Usage notes
  > - Each `<section>` should be identified, typically by including a heading (`<h1>`-`<h6>` element) as a child of the `<section>` element.
  > - If it makes sense to separately syndicate the content of a `<section>` element, use an `<article> `element instead.
  > - Do not use the `<section>` element as a generic container; this is what `<div>` is for, especially when the sectioning is only for styling purposes. A rule of thumb is that a section should logically appear in the outline of a document.
  [Source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#Usage_notes)

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-09-28 13:28 UTC, bolah2009 commented on style.css
> +	color: #000 !important;
#### `REQUIRED`

#### The use of `!important` here is not necessary. Please remove it.






Always look for a way to use [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) before even considering `!important`. 

Learn more [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception)

> Make sure you DON’T make [common mistakes](https://speckyboy.com/good-bad-css-practices/) in your CSS styles.

> **Recommendation:** You should only use the `!important` rule when overriding styles in a user style sheet, overriding 3rd party code and inline styles as well as utility classes.

2019-09-28 13:28 UTC, bolah2009 commented on style.css
> +	color: #000 !important;
This `!important` can be removed too. As explained above a more specific rule in [Line 295](https://github.com/wickathou/new-york-times/blob/d91b57dfdb1d0870654ea7afb1aa774a9400f20f/style.css#L295) will prevent this line from working if you remove the `!important` and also line 295 is currently useless because of the `!important` rule.

You can decide which rule you want to keep without using `!important`. Delete Line 102 or 295. 

https://github.com/wickathou/new-york-times/blob/d91b57dfdb1d0870654ea7afb1aa774a9400f20f/style.css#L293-L297

2019-09-28 13:28 UTC, bolah2009 commented on index.html
> +			<section class="navbar-container margin-center navbar-container-padding">
Why are we using the `section` element for navbar? :thinking: 

It would be better to use the `nav` element here instead.

2019-09-28 13:33 UTC, bolah2009 reviewed
# Let's make this Pull Request look more professional.
  - [NEXT PROJECT]: Use meaningful commits messages. [Learn more here](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) and Check [this awesome article](https://chris.beams.io/posts/git-commit/)
  - [REQUIRED] Use meaningful names for  Pull Requests.
  - [REQUIRED] Add a short summary of changes in Pull Request description.
- [NEXT PROJECTS]: For next (HTML/CSS) project, please follow `GitHub flow` [guidelines](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). What is missing here is a descriptive branch name instead of `structure`.

# Rename PR
  ![rename PR](https://user-images.githubusercontent.com/36057474/63838245-ec569f80-c974-11e9-93a9-83a4db5c259f.gif)
-----
# Update PR description
  ![update-PR-description-html](https://user-images.githubusercontent.com/36057474/64305800-6e078800-cf88-11e9-82f0-04e13fd6cb8d.gif)

2019-09-30 16:30 UTC, wickathou commented on index.html
> +			<section class="navbar-container margin-center navbar-container-padding">
It was mainly because that's the structure they have on the original page. They use section instead of div on most of the text. I think that it's for SEO purposes, which maybe we using W3C validator as our God, might be stop us from understanding why the NYT uses it like that, when their business relies on SEO.

2019-09-30 16:40 UTC, wickathou commented
- Fixed positioning of footer and navbar
- Removed !important CSS rules
- a tags added to logo
- W3C review, fixed warnings

2019-09-30 18:24 UTC, ebukaume commented
Hello @wickathou  and @jfariasf :wave: 

You guys have come a long way. I must commend your efforts. Personally I think you guys have done a great job but unfortunately, **there is a requirement for this project that is not met yet.**

- [ ] Comments: It’s better to delete commented code. (If you need to review a previous version of your code, use git history.)

[OPTIONAL]
Your README is clearly better than before, however, you will agree with me that the succession of the headings is not in order (h2 > h2 > h1 > h1 > h1 > h3 > h2 > h2 > h2). You guys can do better with the headings hierachy. 

**Kindly submit another code review request when you have fixed the above issue.**

2019-09-30 21:17 UTC, wickathou commented
- Removed commented CSS rule on line L31

2019-09-30 21:37 UTC, Redvanisation approved these changes
### Hello @wickathou and @jfariasf  🌟 

### _Nice work on this project, it seems that you guys have met all the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

2019-09-30 21:43 UTC, merged

2019-10-01 21:22 UTC, bolah2009 commented on index.html
> +			<section class="navbar-container margin-center navbar-container-padding">
What do you mean by '...we using W3C validator as our God'?

I referenced MDN usage notes of `section` element in the main review.

How will `nav` element for the page main navigation link affects SEO compared with the use of section?

2019-10-01 21:37 UTC, wickathou commented on index.html
> +			<section class="navbar-container margin-center navbar-container-padding">
I don't know man, but if NYT is doing it, I don't think is by mistake or because they forgot to run the W3C validator.